### ISSUE TITLE
Can't build after clone, give error of "ERROR [github.com/hbstack/header/modules/git-org] failed to get remote resource: failed to fetch remote resource: Unauthorized Built in 17666 ms"

### ISSUE THREAD

**Issue by creditket** [hbstack/site#758]
Is this a paid version?  Thank you.

**Comment by razonyang** [comment]
No, you can either remove the github.com/hbstack/header/modules/git-org or specify GITHUB_TOKEN environment variable that used to fetch stars count of repos.

**Comment by creditket** [comment]
is the github.com/hbstack/anti-adblock also open source ?

**Comment by razonyang** [comment]
> is the github.com/hbstack/anti-adblock also open source ?

It is not, it's a private module.

**Comment by razonyang** [comment]
Hi, thanks for interesting in this project, if you want to contribute to the docs, you can also edit it on [CMS](https://hbstack.dev/admin/).

If you're trying to install the theme, I don't recommend cloning this repo, it contains too many things you don't need.

I'm closing this issue, please feel free to open another if you encountered an issue.
