### ISSUE TITLE
Show every config in one page

### ISSUE THREAD

**Issue by TetraTheta** [hbstack/site#770]
It would be nice to see 'All-in-one config page' in the site with those config's default value.

With it, people don't need to navigate every module page for updating their config to latest.

<pre class="language-yaml"><code class="language-yaml">#hugo.yaml
params:
  hb:
    <a href="https://hbstack.dev/modules/hb/#site-parameters">css_bundle_name</a>: hb
    <a href="https://hbstack.dev/modules/hb/#site-parameters">color</a>: light
    <a href="https://hbstack.dev/modules/hb/#site-parameters">debug</a>: false
    <a href="https://hbstack.dev/modules/hb/#site-parameters">js_bundle_name</a>: hb
    <a href="https://hbstack.dev/modules/hb/#site-parameters">logo</a>: images/logo.png
    <a href="https://hbstack.dev/modules/hb/#site-parameters">full_width</a>: false
    header:
      <a href="https://hbstack.dev/modules/header/overview/#site-parameters">brand</a>: ""
      <a href="https://hbstack.dev/modules/header/overview/#site-parameters">breakpoint</a>: lg
      <a href="https://hbstack.dev/modules/header/overview/#site-parameters">full_width</a>: true
      <a href="https://hbstack.dev/modules/header/overview/#site-parameters">logo_bg</a>: indigo
      <a href="https://hbstack.dev/modules/header/overview/#site-parameters">menus_alignment</a>: start
      <a href="https://hbstack.dev/modules/header/overview/#site-parameters">sticky</a>: true</code></pre>

This is breif example for Core Module and Header module.

**Comment by razonyang** [comment]
It's modular, I don't think user will import all the modules, this is not a good way to go.

**Comment by TetraTheta** [comment]
That's why I added link for module page to every config key. User can click the link to see if the config is related to their site or not. That AIO page is for simple reference.

Maybe specifying the module with comment would be good for that information, like this:
```yaml
# hugo.yaml
params:
  hb:
    css_bundle_name: hb # hb
    # ...
    header:
      brand: "" # header
      socials: # header/socials
```
But since those configs are categorized fairly intuitive, I'm not sure those comment would be actually useful or not.

**Comment by razonyang** [comment]
> But since those configs are categorized fairly intuitive, I'm not sure those comment would be actually useful or not.

I think it's not very helpful.

It may be helpful that to make the evey params to be a heading, so that user can search/locate the parameter, take [images.hugomods.com](https://images.hugomods.com) as an example.

![image](https://github.com/hbstack/site/assets/17720932/08c9cec4-d62f-44d4-9af1-4465c6153bdd)

**Comment by TetraTheta** [comment]
I think that's good too!
